---
title: "statistic_testing"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(stargazer)
library(pheatmap)
library(plm)
```

```{r}

df_award <- read.csv('data/wrd_04_all-data.csv')
df_wipo <- read.csv('data/wipo_design.csv')

summary(df_wipo)
```

```{r}
df_wipo %>%
  mutate(
    wipo_period = paste(wipo_year_from, wipo_year_to, sep = " - ")
  ) %>%
  group_by(wipo_period) %>%
  summarise(frecuencia = n(), .groups = "drop") %>%
  ggplot(aes(x = wipo_period, y = frecuencia)) +
  geom_col(fill = 'steelblue') +
  labs(title = "Número de registros por año", x = "Año", y = "Frecuencia") +
  guides(x =  guide_axis(angle = 90)) +
  theme_minimal()
```

```{r}
df_nuevo <- df_award %>%
  mutate(
    award_fyear = as.numeric(str_extract(award_period, '\\d{4}$'))
  ) %>%
  filter(award_fyear > 2014 & award_fyear < 2023)

length(unique(df_nuevo$designer_country))
```

```{r}

length(unique(df_wipo$country_code, na.rm = T))
```

```{r}

dir <- './data/results/correlations_tables/'

dir_T2 <- '2015-2019/'
dir_T3 <- '2020-2024/'
dir_Total <- 'Total/'
dir_fix <- 'Fixed Effects/'

subdir_org <- 'Awards-WIPO/'
subdir_alt <- 'Symbolic-Synthetic/'

p <- function(..., sep='') {
    paste(..., sep=sep, collapse=sep)
}
```

```{r}
 
df_T2 <- read.csv('./test/DataFrame_2015_2019.csv') %>%
  select(-X) %>%
  mutate(
    log_pib = log(PIB_per_capita, base = 10),
    log_f23 = log(F23_2018, base = 10),
    log_f25 = log(F25_2018, base = 10),
    year = 0
  ) %>%
  filter(
    !is.na(DCI_awards * DCI_wipo)
  )

df_T3 <- read.csv('./test/DataFrame_2020_2024.csv') %>%
  select(-X) %>%
  mutate(
    log_pib = log(PIB_per_capita, base = 10),
    log_f23 = log(F23_2018, base = 10),
    log_f25 = log(F25_2018, base = 10),
    year = 1
  ) %>%
  filter(
    !is.na(DCI_awards * DCI_wipo)
  )

df_Total <- read.csv('./test/DataFrame_total.csv') %>%
  select(-X) %>%
  mutate(
    log_pib = log(PIB_per_capita, base = 10),
    log_f23 = log(F23_2018, base = 10),
    log_f25 = log(F25_2018, base = 10)
  ) %>%
  filter(
    !is.na(DCI_awards * DCI_wipo)
  )
```

```{r}

lm_wipo_T2 <- lm(
  DCI_wipo ~ DCI_awards, data = df_T2
)

lm_wipo_T3 <- lm(
  DCI_wipo ~ DCI_awards, data = df_T3
)

lm_wipo_Total <- lm(
  DCI_wipo ~ DCI_awards, data = df_Total
)

df_T2$predicted_WIPO <- predict(lm_wipo_T2, newdata = df_T2)
df_T2$DCI_synthetic <- df_T2$DCI_wipo - df_T2$predicted_WIPO
df_T2$DCI_symbolic <- df_T2$DCI_awards

df_T3$predicted_WIPO <- predict(lm_wipo_T3, newdata = df_T3)
df_T3$DCI_synthetic <- df_T3$DCI_wipo - df_T3$predicted_WIPO
df_T3$DCI_symbolic <- df_T3$DCI_awards

df_Total$predicted_WIPO <- predict(lm_wipo_Total, newdata = df_Total)
df_Total$DCI_synthetic <- df_Total$DCI_wipo - df_Total$predicted_WIPO
df_Total$DCI_symbolic <- df_Total$DCI_awards


df_unido <- rbind(df_T2, df_T3) %>%
  mutate(year = as.factor(year)) %>%
  filter(
    !is.na(DCI_awards * DCI_wipo)
  )

DFs <- list(df_T2, df_T3, df_Total)
Nombres <- list(dir_T2, dir_T3, dir_Total)
```

```{r}

ggplot(data = df_Total, aes(x = DCI_symbolic, y = DCI_synthetic)) +
  geom_point() +
  geom_smooth(method = 'lm') + 
  labs(x = 'DCI wipo', y = 'DCI_awards') +
  theme_minimal()

```

### Modelos OLS

#### Awards-WIPO

```{r}

#Modelo estático para Times

for (i in 1:3){
  modelo_1 <- lm(
  log_pib ~ DCI_awards, data = DFs[[i]]
)

modelo_2 <- lm(
  log_pib ~ DCI_wipo, data = DFs[[i]]
)

modelo_3 <- lm(
  log_pib ~ DCI_awards + DCI_wipo, data = DFs[[i]]
)

modelo_4 <- lm(
  log_pib ~ DCI_awards + DCI_wipo + DCI_awards * DCI_wipo, data = DFs[[i]]
)

stargazer(modelo_1, modelo_2, modelo_3, modelo_4, type = 'text',
          covariate.labels = c('DCI Awards', 'DCI WIPO', 'Interacción', 'Constante'),
          dep.var.labels = c("Log(PIB per capita)"),
          out = p(dir, Nombres[[i]], subdir_org, 'log_pib.txt'))
}

```

```{r}

#Modelo estático para Times

for (i in 1:3){
  modelo_1 <- lm(
  Times_Score ~ DCI_awards, data = DFs[[i]]
)

modelo_2 <- lm(
  Times_Score ~ DCI_wipo, data = DFs[[i]]
)

modelo_3 <- lm(
  Times_Score ~ DCI_awards + DCI_wipo, data = DFs[[i]]
)

modelo_4 <- lm(
  Times_Score ~ DCI_awards + DCI_wipo + DCI_awards * DCI_wipo, data = DFs[[i]]
)

stargazer(modelo_1, modelo_2, modelo_3, modelo_4, type = 'text',
          covariate.labels = c('DCI Awards', 'DCI WIPO', 'Interacción', 'Constante'),
          dep.var.labels = c("Log(Puntaje de Ins. Educativas)"),
          out = p(dir, Nombres[[i]], subdir_org, 'times_score.txt'))
}

```

```{r}

#Modelo estático para Alex

for (i in 1:3){
  modelo_1 <- lm(
  Alex_Score ~ DCI_awards, data = DFs[[i]]
)

modelo_2 <- lm(
  Alex_Score ~ DCI_wipo, data = DFs[[i]]
)

modelo_3 <- lm(
  Alex_Score ~ DCI_awards + DCI_wipo, data = DFs[[i]]
)

modelo_4 <- lm(
  Alex_Score ~ DCI_awards + DCI_wipo + DCI_awards * DCI_wipo, data = DFs[[i]]
)

stargazer(modelo_1, modelo_2, modelo_3, modelo_4, type = 'text',
          covariate.labels = c('DCI Awards', 'DCI WIPO', 'Interacción', 'Constante'),
          dep.var.labels = c("Log(Publicaciones de Ins. Educativas)"),
          out = p(dir, Nombres[[i]], subdir_org, 'alex_score.txt'))

}

```

```{r}

#Modelo estático para Alex

for (i in 1:3){
  modelo_1 <- lm(
  Alex_Score ~ DCI_awards, data = DFs[[i]]
)

modelo_2 <- lm(
  Alex_Score ~ DCI_wipo, data = DFs[[i]]
)

modelo_3 <- lm(
  Alex_Score ~ DCI_awards + DCI_wipo, data = DFs[[i]]
)

modelo_4 <- lm(
  Alex_Score ~ DCI_awards + DCI_wipo + DCI_awards * DCI_wipo, data = DFs[[i]]
)

stargazer(modelo_1, modelo_2, modelo_3, modelo_4, type = 'text',
          covariate.labels = c('DCI Awards', 'DCI WIPO', 'Interacción', 'Constante'),
          dep.var.labels = c("Log(Publicaciones de Ins. Educativas)"),
          out = p(dir, Nombres[[i]], subdir_org, 'alex_score.txt'))

}

```

#### Simbólico-Sintético

```{r}
#Modelo estático para PIB per capita

for (i in 1:3) {
modelo_1 <- lm(
  log_pib ~ DCI_symbolic, data = DFs[[i]]
)

modelo_2 <- lm(
  log_pib ~ DCI_synthetic, data = DFs[[i]]
)

modelo_3 <- lm(
  log_pib ~ DCI_symbolic + DCI_synthetic, data = DFs[[i]]
)

modelo_4 <- lm(
  log_pib ~ DCI_symbolic + DCI_synthetic + DCI_symbolic * DCI_synthetic, data = DFs[[i]]
)

stargazer(modelo_1, modelo_2, modelo_3, modelo_4, type = 'text',
          covariate.labels = c('DCI Simbolico', 'DCI Sintético', 'Interacción', 'Constante'),
          dep.var.labels = c("Log(PIB per capita)"),
          out = p(dir, Nombres[[i]], subdir_alt, 'log_pib.txt'))
}
```

```{r}

#Modelo estático para Alex
for (i in 1:3) {
modelo_1 <- lm(
  Alex_Score ~ DCI_symbolic, data = DFs[[i]]
)

modelo_2 <- lm(
  Alex_Score ~ DCI_synthetic, data = DFs[[i]]
)

modelo_3 <- lm(
  Alex_Score ~ DCI_symbolic + DCI_synthetic, data = DFs[[i]]
)

modelo_4 <- lm(
  Alex_Score ~ DCI_symbolic + DCI_synthetic + DCI_symbolic * DCI_synthetic, data = DFs[[i]]
)

stargazer(modelo_1, modelo_2, modelo_3, modelo_4, type = 'text',
          covariate.labels = c('DCI Simbolico', 'DCI Sintético', 'Interacción', 'Constante'),
          dep.var.labels = c("Log(Publicaciones de Ins. Educativas)"),
          out = p(dir, Nombres[[i]], subdir_alt, 'alex_score.txt'))
}
```

```{r}

#Modelo estático para Times
for (i in 1:3) {
modelo_1 <- lm(
  Times_Score ~ DCI_symbolic, data = DFs[[i]]
)

modelo_2 <- lm(
  Times_Score ~ DCI_synthetic, data = DFs[[i]]
)

modelo_3 <- lm(
  Times_Score ~ DCI_symbolic + DCI_synthetic, data = DFs[[i]]
)

modelo_4 <- lm(
  Times_Score ~ DCI_symbolic + DCI_synthetic + DCI_symbolic * DCI_synthetic, data = DFs[[i]]
)

stargazer(modelo_1, modelo_2, modelo_3, modelo_4, type = 'text',
          covariate.labels = c('DCI Simbolico', 'DCI Sintético', 'Interacción', 'Constante'),
          dep.var.labels = c("Log(Puntaje de Ins. Educativas)"),
          out = p(dir, Nombres[[i]], subdir_alt, 'times_score.txt'))
}
```

### Fixed Effects

#### Awards-WIPO

```{r}

modelo_1 <- plm(log_pib ~ DCI_awards, data = df_unido, index = c("País"), model = "within")

modelo_2 <- plm(log_pib ~ DCI_wipo, data = df_unido, index = c("País"), model = "within")

modelo_3 <- plm(log_pib ~ DCI_awards + DCI_wipo, data = df_unido, index = c("País"), model = "within")

modelo_4 <- plm(log_pib ~ DCI_awards + DCI_awards * DCI_wipo + DCI_wipo, data = df_unido, index = c("País"), model = "within")

modelo_5 <- plm(log_pib ~ DCI_awards + DCI_awards * DCI_wipo + DCI_wipo + year, data = df_unido, index = c("País", "year"), model = "within")

stargazer(modelo_1, modelo_2, modelo_3, modelo_4, modelo_5, type = 'text',
          covariate.labels = c('DCI Awards', 'DCI WIPO', 'Tiempo', 'Interacciónn'),
          dep.var.labels = c("Log(PIB per capita)"),
          out = p(dir, dir_fix, subdir_org, 'log_pib.txt'))

```

```{r}

modelo_1 <- plm(Alex_Score ~ DCI_awards, data = df_unido, index = c("País"), model = "within")

modelo_2 <- plm(Alex_Score ~ DCI_wipo, data = df_unido, index = c("País"), model = "within")

modelo_3 <- plm(Alex_Score ~ DCI_awards + DCI_wipo, data = df_unido, index = c("País"), model = "within")

modelo_4 <- plm(Alex_Score ~ DCI_awards + DCI_awards * DCI_wipo + DCI_wipo, data = df_unido, index = c("País"), model = "within")

modelo_5 <- plm(Alex_Score ~ DCI_awards + DCI_awards * DCI_wipo + DCI_wipo + year, data = df_unido, index = c("País", "year"), model = "within")

stargazer(modelo_1, modelo_2, modelo_3, modelo_4, modelo_5, type = 'text',
          covariate.labels = c('DCI Awards', 'DCI WIPO', 'Tiempo', 'Interacciónn'),
          dep.var.labels = c("Log(Publicaciones por Ins. Educativa)"),
          out = p(dir, dir_fix, subdir_org, 'alex_score.txt'))

```

```{r}

modelo_1 <- plm(Times_Score ~ DCI_awards, data = df_unido, index = c("País"), model = "within")

modelo_2 <- plm(Times_Score ~ DCI_wipo, data = df_unido, index = c("País"), model = "within")

modelo_3 <- plm(Times_Score ~ DCI_awards + DCI_wipo, data = df_unido, index = c("País"), model = "within")

modelo_4 <- plm(Times_Score ~ DCI_awards + DCI_awards * DCI_wipo + DCI_wipo, data = df_unido, index = c("País"), model = "within")

modelo_5 <- plm(Times_Score ~ DCI_awards + DCI_awards * DCI_wipo + DCI_wipo + year, data = df_unido, index = c("País", "year"), model = "within")

stargazer(modelo_1, modelo_2, modelo_3, modelo_4, modelo_5, type = 'text',
          covariate.labels = c('DCI Awards', 'DCI WIPO', 'Tiempo', 'Interacciónn'),
          dep.var.labels = c("Log(Puntaje por Ins. Educativa)"),
          out = p(dir, dir_fix, subdir_org, 'times_score.txt'))

```

#### Simbólico-Sintético

```{r}

modelo_1 <- plm(log_pib ~ DCI_symbolic, data = df_unido, index = c("País"), model = "within")

modelo_2 <- plm(log_pib ~ DCI_synthetic , data = df_unido, index = c("País"), model = "within")

modelo_3 <- plm(log_pib ~ DCI_symbolic + DCI_synthetic, data = df_unido, index = c("País"), model = "within")

modelo_4 <- plm(log_pib ~ DCI_symbolic + DCI_symbolic * DCI_synthetic + DCI_synthetic, data = df_unido, index = c("País"), model = "within")

modelo_5 <- plm(log_pib ~ DCI_symbolic + DCI_symbolic * DCI_synthetic + DCI_synthetic + year, data = df_unido, index = c("País", "year"), model = "within")

stargazer(modelo_1, modelo_2, modelo_3, modelo_4, modelo_5, type = 'text',
          covariate.labels = c('DCI Simbólico', 'DCI Sintético', 'Tiempo', 'Interacción'),
          dep.var.labels = c("Log(PIB per capita)"),
          out = p(dir, dir_fix, subdir_alt, 'log_pib.txt'))

```

```{r}

modelo_1 <- plm(Alex_Score ~ DCI_symbolic, data = df_unido, index = c("País"), model = "within")

modelo_2 <- plm(Alex_Score ~ DCI_synthetic , data = df_unido, index = c("País"), model = "within")

modelo_3 <- plm(Alex_Score ~ DCI_symbolic + DCI_synthetic, data = df_unido, index = c("País"), model = "within")

modelo_4 <- plm(Alex_Score ~ DCI_symbolic + DCI_symbolic * DCI_synthetic + DCI_synthetic, data = df_unido, index = c("País"), model = "within")

modelo_5 <- plm(Alex_Score ~ DCI_symbolic + DCI_symbolic * DCI_synthetic + DCI_synthetic + year, data = df_unido, index = c("País", "year"), model = "within")

stargazer(modelo_1, modelo_2, modelo_3, modelo_4, modelo_5, type = 'text',
          covariate.labels = c('DCI Simbólico', 'DCI Sintético', 'Tiempo', 'Interacción'),
          dep.var.labels = c("Log(Publicaciones por Ins. Educativa)"),
          out = p(dir, dir_fix, subdir_alt, 'alex_score.txt'))

```

```{r}

modelo_1 <- plm(Times_Score ~ DCI_symbolic, data = df_unido, index = c("País"), model = "within")

modelo_2 <- plm(Times_Score ~ DCI_synthetic , data = df_unido, index = c("País"), model = "within")

modelo_3 <- plm(Times_Score ~ DCI_symbolic + DCI_synthetic, data = df_unido, index = c("País"), model = "within")

modelo_4 <- plm(Times_Score ~ DCI_symbolic + DCI_symbolic * DCI_synthetic + DCI_synthetic, data = df_unido, index = c("País"), model = "within")

modelo_5 <- plm(Times_Score ~ DCI_symbolic + DCI_symbolic * DCI_synthetic + DCI_synthetic + year, data = df_unido, index = c("País", "year"), model = "within")

stargazer(modelo_1, modelo_2, modelo_3, modelo_4, modelo_5, type = 'text',
          covariate.labels = c('DCI Simbólico', 'DCI Sintético', 'Tiempo', 'Interacción'),
          dep.var.labels = c("Log(Puntaje por Ins. Educativa)"),
          out = p(dir, dir_fix, subdir_alt, 'times_score.txt'))

```

```{r}
corruwu <- cor(df_Total[, c('DCI_awards', 'DCI_awards', 'ECI_tr', 'ECI_te', 'ECI_rs')]) - diag(5)
```

```{r}

pheatmap(corruwu, 
         color = colorRampPalette(c("white", "red2"))(20),
         breaks = seq(0, 1, length.out = 20),
         main = "Matriz de Correlación",
         angle_col = 45)
```

```{r}



```
