awards_iso = {
    "Albania": "AL",
    "Argentina": "AR",
    "Armenia": "AM",
    "Australia": "AU",
    "Austria": "AT",
    "Azerbaijan": "AZ",
    "Bahrain": "BH",
    "Bangladesh": "BD",
    "Belarus": "BY",
    "Belgium": "BE",
    "Bosnia and Herzegovina": "BA",
    "Botswana": "BW",
    "Brazil": "BR",
    "Bulgaria": "BG",
    "Cameroon": "CM",
    "Canada": "CA",
    "Cayman Islands": "KY",
    "Chile": "CL",
    "China": "CN",
    "Chinese Taipei": "TW",
    "Colombia": "CO",
    "Costa Rica": "CR",
    "Croatia": "HR",
    "Cuba": "CU",
    "Cyprus": "CY",
    "Czechia": "CZ",
    "Denmark": "DK",
    "Dominican Republic": "DO",
    "Ecuador": "EC",
    "Egypt": "EG",
    "Estonia": "EE",
    "Faroe Islands": "FO",
    "Finland": "FI",
    "France": "FR",
    "Georgia": "GE",
    "Germany": "DE",
    "Greece": "GR",
    "Guatemala": "GT",
    "Hong Kong": "HK",
    "Hungary": "HU",
    "Iceland": "IS",
    "India": "IN",
    "Indonesia": "ID",
    "Iran": "IR",
    "Ireland": "IE",
    "Israel": "IL",
    "Italy": "IT",
    "Japan": "JP",
    "Jordan": "JO",
    "Kazakhstan": "KZ",
    "Kenya": "KE",
    "Kosovo": "XK",
    "Kuwait": "KW",
    "Kyrgyzstan": "KG",
    "Laos": "LA",
    "Latvia": "LV",
    "Lebanon": "LB",
    "Liechtenstein": "LI",
    "Lithuania": "LT",
    "Luxembourg": "LU",
    "Macau (China)": "MO",
    "Macedonia": "MK",
    "Malaysia": "MY",
    "Maldives": "MV",
    "Malta": "MT",
    "Mexico": "MX",
    "Moldova": "MD",
    "Monaco": "MC",
    "Mongolia": "MN",
    "Montenegro": "ME",
    "Morocco": "MA",
    "Netherlands": "NL",
    "New Zealand": "NZ",
    "Nicaragua": "NI",
    "North Korea": "KP",
    "Norway": "NO",
    "Oman": "OM",
    "Pakistan": "PK",
    "Palestine": "PS",
    "Paraguay": "PY",
    "Peru": "PE",
    "Philippines": "PH",
    "Poland": "PL",
    "Portugal": "PT",
    "Puerto Rico": "PR",
    "Qatar": "QA",
    "Romania": "RO",
    "Russia": "RU",
    "Saudi Arabia": "SA",
    "Serbia": "RS",
    "Singapore": "SG",
    "Slovakia": "SK",
    "Slovenia": "SI",
    "South Africa": "ZA",
    "South Korea": "KR",
    "Spain": "ES",
    "Sri Lanka": "LK",
    "Swaziland": "SZ",
    "Sweden": "SE",
    "Switzerland": "CH",
    "Taiwan": "TW",
    "Tajikistan": "TJ",
    "Tanzania": "TZ",
    "Thailand": "TH",
    "Trinidad and Tobago": "TT",
    "Tunisia": "TN",
    "Turkey": "TR",
    "Ukraine": "UA",
    "United Arab Emirates": "AE",
    "United Kingdom": "GB",
    "United States": "US",
    "Uruguay": "UY",
    "Venezuela": "VE",
    "Vietnam": "VN",
    "Zimbabwe": "ZW"
}

wipo_iso  = {
    "Albania": "AL",
    "Algeria": "DZ",
    "Andorra": "AD",
    "Antigua and Barbuda": "AG",
    "Argentina": "AR",
    "Armenia": "AM",
    "Australia": "AU",
    "Austria": "AT",
    "Azerbaijan": "AZ",
    "Bahamas": "BS",
    "Bahrain": "BH",
    "Bangladesh": "BD",
    "Barbados": "BB",
    "Belarus": "BY",
    "Belgium": "BE",
    "Belize": "BZ",
    "Benin": "BJ",
    "Bhutan": "BT",
    "Bolivia (Plurinational State of)": "BO",
    "Bonaire, Saint Eustatius and Saba": "BQ",
    "Bosnia and Herzegovina": "BA",
    "Botswana": "BW",
    "Brazil": "BR",
    "Brunei Darussalam": "BN",
    "Bulgaria": "BG",
    "Burkina Faso": "BF",
    "Burundi": "BI",
    "Cambodia": "KH",
    "Cameroon": "CM",
    "Canada": "CA",
    "Central African Republic": "CF",
    "Chad": "TD",
    "Chile": "CL",
    "China": "CN",
    "Colombia": "CO",
    "Comoros": "KM",
    "Congo": "CG",
    "Costa Rica": "CR",
    "Croatia": "HR",
    "Cuba": "CU",
    "Curacao": "CW",
    "Cyprus": "CY",
    "Czech Republic": "CZ",
    "Côte d'Ivoire": "CI",
    "Democratic Republic of the Congo": "CD",
    "Denmark": "DK",
    "Djibouti": "DJ",
    "Dominica": "DM",
    "Dominican Republic": "DO",
    "Ecuador": "EC",
    "Egypt": "EG",
    "El Salvador": "SV",
    "Equatorial Guinea": "GQ",
    "Estonia": "EE",
    "Eswatini": "SZ",
    "Ethiopia": "ET",
    "Finland": "FI",
    "France": "FR",
    "Gabon": "GA",
    "Gambia": "GM",
    "Georgia": "GE",
    "Germany": "DE",
    "Germany (West)": "DE",
    "Ghana": "GH",
    "Greece": "GR",
    "Grenada": "GD",
    "Guatemala": "GT",
    "Guinea": "GN",
    "Guyana": "GY",
    "Haiti": "HT",
    "Holy See": "VA",
    "Honduras": "HN",
    "Hungary": "HU",
    "Iceland": "IS",
    "India": "IN",
    "Indonesia": "ID",
    "Iran (Islamic Republic of)": "IR",
    "Iraq": "IQ",
    "Ireland": "IE",
    "Israel": "IL",
    "Italy": "IT",
    "Jamaica": "JM",
    "Japan": "JP",
    "Jordan": "JO",
    "Kazakhstan": "KZ",
    "Kenya": "KE",
    "Korea (Democratic People's Republic of)": "KP",
    "Korea (Republic of)": "KR",
    "Kyrgyzstan": "KG",
    "Lao People's Democratic Republic": "LA",
    "Latvia": "LV",
    "Lebanon": "LB",
    "Lesotho": "LS",
    "Liberia": "LR",
    "Libya (State of)": "LY",
    "Liechtenstein": "LI",
    "Lithuania": "LT",
    "Luxembourg": "LU",
    "Madagascar": "MG",
    "Malawi": "MW",
    "Malaysia": "MY",
    "Mali": "ML",
    "Malta": "MT",
    "Mauritania": "MR",
    "Mauritius": "MU",
    "Mexico": "MX",
    "Moldova (Republic of)": "MD",
    "Monaco": "MC",
    "Mongolia": "MN",
    "Montenegro": "ME",
    "Morocco": "MA",
    "Mozambique": "MZ",
    "Namibia": "NA",
    "Nepal": "NP",
    "Netherlands": "NL",
    "New Zealand": "NZ",
    "Nicaragua": "NI",
    "Niger": "NE",
    "Nigeria": "NG",
    "North Macedonia (Republic of)": "MK",
    "Norway": "NO",
    "Oman": "OM",
    "Pakistan": "PK",
    "Panama": "PA",
    "Papua New Guinea": "PG",
    "Paraguay": "PY",
    "Peru": "PE",
    "Philippines": "PH",
    "Poland": "PL",
    "Portugal": "PT",
    "Qatar": "QA",
    "Romania": "RO",
    "Russian Federation": "RU",
    "Rwanda": "RW",
    "Saint Kitts and Nevis": "KN",
    "Saint Lucia": "LC",
    "Saint Vincent and the Grenadines": "VC",
    "Samoa": "WS",
    "San Marino": "SM",
    "Sao Tome and Principe": "ST",
    "Saudi Arabia": "SA",
    "Senegal": "SN",
    "Serbia": "RS",
    "Serbia and Montenegro": "CS",
    "Seychelles": "SC",
    "Sierra Leone": "SL",
    "Singapore": "SG",
    "Sint Maarten (Dutch part)": "SX",
    "Slovakia": "SK",
    "Slovenia": "SI",
    "South Africa": "ZA",
    "Spain": "ES",
    "Sri Lanka": "LK",
    "Sudan": "SD",
    "Suriname": "SR",
    "Sweden": "SE",
    "Switzerland": "CH",
    "Syrian Arab Republic": "SY",
    "Tajikistan": "TJ",
    "Tanzania (United Republic of)": "TZ",
    "Togo": "TG",
    "Tonga": "TO",
    "Trinidad and Tobago": "TT",
    "Tunisia": "TN",
    "Turkey": "TR",
    "Turkmenistan": "TM",
    "Uganda": "UG",
    "Ukraine": "UA",
    "United Arab Emirates": "AE",
    "United Kingdom": "GB",
    "United States of America": "US",
    "Uruguay": "UY",
    "Uzbekistan": "UZ",
    "Venezuela (Bolivarian Republic of)": "VE",
    "Viet Nam": "VN",
    "Yemen": "YE",
    "Zambia": "ZM",
    "Zimbabwe": "ZW"
}

awards_gdp =  {
    "Albania": "Albania",
    "Argentina": "Argentina",
    "Armenia": "Armenia",
    "Australia": "Australia",
    "Austria": "Austria",
    "Azerbaijan": "Azerbaijan",
    "Bahrain": "Bahrain",
    "Bangladesh": "Bangladesh",
    "Belarus": "Belarus",
    "Belgium": "Belgium",
    "Bosnia and Herzegovina": "Bosnia and Herzegovina",
    "Botswana": "Botswana",
    "Brazil": "Brazil",
    "Bulgaria": "Bulgaria",
    "Cameroon": "Cameroon",
    "Canada": "Canada",
    "Cayman Islands": None,
    "Chile": "Chile",
    "China": "China",
    "Chinese Taipei": "Taiwan Province of China",
    "Colombia": "Colombia",
    "Costa Rica": "Costa Rica",
    "Croatia": "Croatia",
    "Cuba": None,
    "Cyprus": "Cyprus",
    "Czechia": "Czech Republic",
    "Denmark": "Denmark",
    "Dominican Republic": "Dominican Republic",
    "Ecuador": "Ecuador",
    "Egypt": "Egypt",
    "Estonia": "Estonia",
    "Faroe Islands": None,
    "Finland": "Finland",
    "France": "France",
    "Georgia": "Georgia",
    "Germany": "Germany",
    "Greece": "Greece",
    "Guatemala": "Guatemala",
    "Hong Kong": "Hong Kong SAR",
    "Hungary": "Hungary",
    "Iceland": "Iceland",
    "India": "India",
    "Indonesia": "Indonesia",
    "Iran": "Islamic Republic of Iran",
    "Ireland": "Ireland",
    "Israel": "Israel",
    "Italy": "Italy",
    "Japan": "Japan",
    "Jordan": "Jordan",
    "Kazakhstan": "Kazakhstan",
    "Kenya": "Kenya",
    "Kosovo": "Kosovo",
    "Kuwait": "Kuwait",
    "Kyrgyzstan": "Kyrgyz Republic",
    "Laos": "Lao P.D.R.",
    "Latvia": "Latvia",
    "Lebanon": "Lebanon",
    "Liechtenstein": None,
    "Lithuania": "Lithuania",
    "Luxembourg": "Luxembourg",
    "Macau (China)": "Macao SAR",
    "Macedonia": "North Macedonia",
    "Malaysia": "Malaysia",
    "Maldives": "Maldives",
    "Malta": "Malta",
    "Mexico": "Mexico",
    "Moldova": "Moldova",
    "Monaco": None,
    "Mongolia": "Mongolia",
    "Montenegro": "Montenegro",
    "Morocco": "Morocco",
    "Netherlands": "Netherlands",
    "New Zealand": "New Zealand",
    "Nicaragua": "Nicaragua",
    "North Korea": "Korea",
    "Norway": "Norway",
    "Oman": "Oman",
    "Pakistan": "Pakistan",
    "Palestine": "West Bank and Gaza",
    "Paraguay": "Paraguay",
    "Peru": "Peru",
    "Philippines": "Philippines",
    "Poland": "Poland",
    "Portugal": "Portugal",
    "Puerto Rico": "Puerto Rico",
    "Qatar": "Qatar",
    "Romania": "Romania",
    "Russia": "Russia",
    "Saudi Arabia": "Saudi Arabia",
    "Serbia": "Serbia",
    "Singapore": "Singapore",
    "Slovakia": "Slovak Republic",
    "Slovenia": "Slovenia",
    "South Africa": "South Africa",
    "South Korea": "Korea",
    "Spain": "Spain",
    "Sri Lanka": "Sri Lanka",
    "Swaziland": "Eswatini",
    "Sweden": "Sweden",
    "Switzerland": "Switzerland",
    "Taiwan": "Taiwan Province of China",
    "Tajikistan": "Tajikistan",
    "Tanzania": "Tanzania",
    "Thailand": "Thailand",
    "Trinidad and Tobago": "Trinidad and Tobago",
    "Tunisia": "Tunisia",
    "Turkey": "Türkiye",
    "Ukraine": "Ukraine",
    "United Arab Emirates": "United Arab Emirates",
    "United Kingdom": "United Kingdom",
    "United States": "United States",
    "Uruguay": "Uruguay",
    "Venezuela": "Venezuela",
    "Vietnam": "Vietnam",
    "Zimbabwe": "Zimbabwe",
}

wipo_gdp = {
    "Albania": "Albania",
    "Algeria": "Algeria",
    "Andorra": "Andorra",
    "Antigua and Barbuda": "Antigua and Barbuda",
    "Argentina": "Argentina",
    "Armenia": "Armenia",
    "Australia": "Australia",
    "Austria": "Austria",
    "Azerbaijan": "Azerbaijan",
    "Bahamas": "The Bahamas",
    "Bahrain": "Bahrain",
    "Bangladesh": "Bangladesh",
    "Barbados": "Barbados",
    "Belarus": "Belarus",
    "Belgium": "Belgium",
    "Belize": "Belize",
    "Benin": "Benin",
    "Bhutan": "Bhutan",
    "Bolivia (Plurinational State of)": "Bolivia",
    "Bonaire, Saint Eustatius and Saba": None,
    "Bosnia and Herzegovina": "Bosnia and Herzegovina",
    "Botswana": "Botswana",
    "Brazil": "Brazil",
    "Brunei Darussalam": "Brunei Darussalam",
    "Bulgaria": "Bulgaria",
    "Burkina Faso": "Burkina Faso",
    "Burundi": "Burundi",
    "Cambodia": "Cambodia",
    "Cameroon": "Cameroon",
    "Canada": "Canada",
    "Central African Republic": "Central African Republic",
    "Chad": "Chad",
    "Chile": "Chile",
    "China": "China",
    "Colombia": "Colombia",
    "Comoros": "Comoros",
    "Congo": "Congo, Republic of",
    "Costa Rica": "Costa Rica",
    "Croatia": "Croatia",
    "Cuba": None,
    "Curacao": None,
    "Cyprus": "Cyprus",
    "Czech Republic": "Czech Republic",
    "Côte d'Ivoire": "Côte d'Ivoire",
    "Democratic Republic of the Congo": "Democratic Republic of the Congo",
    "Denmark": "Denmark",
    "Djibouti": "Djibouti",
    "Dominica": "Dominica",
    "Dominican Republic": "Dominican Republic",
    "Ecuador": "Ecuador",
    "Egypt": "Egypt",
    "El Salvador": "El Salvador",
    "Equatorial Guinea": "Equatorial Guinea",
    "Estonia": "Estonia",
    "Eswatini": "Eswatini",
    "Ethiopia": "Ethiopia",
    "Finland": "Finland",
    "France": "France",
    "Gabon": "Gabon",
    "Gambia": "Gambia, The",
    "Georgia": "Georgia",
    "Germany": "Germany",
    "Germany (West)": None,
    "Ghana": "Ghana",
    "Greece": "Greece",
    "Grenada": "Grenada",
    "Guatemala": "Guatemala",
    "Guinea": "Guinea",
    "Guyana": "Guyana",
    "Haiti": "Haiti",
    "Holy See": None,
    "Honduras": "Honduras",
    "Hungary": "Hungary",
    "Iceland": "Iceland",
    "India": "India",
    "Indonesia": "Indonesia",
    "Iran (Islamic Republic of)": "Islamic Republic of Iran",
    "Iraq": "Iraq",
    "Ireland": "Ireland",
    "Israel": "Israel",
    "Italy": "Italy",
    "Jamaica": "Jamaica",
    "Japan": "Japan",
    "Jordan": "Jordan",
    "Kazakhstan": "Kazakhstan",
    "Kenya": "Kenya",
    "Korea (Democratic People's Republic of)": None,
    "Korea (Republic of)": "Korea",
    "Kyrgyzstan": "Kyrgyz Republic",
    "Lao People's Democratic Republic": "Lao P.D.R.",
    "Latvia": "Latvia",
    "Lebanon": "Lebanon",
    "Lesotho": "Lesotho",
    "Liberia": "Liberia",
    "Libya (State of)": "Libya",
    "Liechtenstein": None,
    "Lithuania": "Lithuania",
    "Luxembourg": "Luxembourg",
    "Madagascar": "Madagascar",
    "Malawi": "Malawi",
    "Malaysia": "Malaysia",
    "Mali": "Mali",
    "Malta": "Malta",
    "Mauritania": "Mauritania",
    "Mauritius": "Mauritius",
    "Mexico": "Mexico",
    "Moldova (Republic of)": "Moldova",
    "Monaco": None,
    "Mongolia": "Mongolia",
    "Montenegro": "Montenegro",
    "Morocco": "Morocco",
    "Mozambique": "Mozambique",
    "Namibia": "Namibia",
    "Nepal": "Nepal",
    "Netherlands": "Netherlands",
    "New Zealand": "New Zealand",
    "Nicaragua": "Nicaragua",
    "Niger": "Niger",
    "Nigeria": "Nigeria",
    "North Macedonia (Republic of)": "North Macedonia",
    "Norway": "Norway",
    "Oman": "Oman",
    "Pakistan": "Pakistan",
    "Panama": "Panama",
    "Papua New Guinea": "Papua New Guinea",
    "Paraguay": "Paraguay",
    "Peru": "Peru",
    "Philippines": "Philippines",
    "Poland": "Poland",
    "Portugal": "Portugal",
    "Qatar": "Qatar",
    "Romania": "Romania",
    "Russian Federation": "Russia",
    "Rwanda": "Rwanda",
    "Saint Kitts and Nevis": "St. Kitts and Nevis",
    "Saint Lucia": "St. Lucia",
    "Saint Vincent and the Grenadines": "St. Vincent and the Grenadines",
    "Samoa": "Samoa",
    "San Marino": "San Marino",
    "Sao Tome and Principe": "São Tomé and Príncipe",
    "Saudi Arabia": "Saudi Arabia",
    "Senegal": "Senegal",
    "Serbia": "Serbia",
    "Serbia and Montenegro": None,
    "Seychelles": "Seychelles",
    "Sierra Leone": "Sierra Leone",
    "Singapore": "Singapore",
    "Sint Maarten (Dutch part)": None,
    "Slovakia": "Slovak Republic",
    "Slovenia": "Slovenia",
    "South Africa": "South Africa",
    "Spain": "Spain",
    "Sri Lanka": "Sri Lanka",
    "Sudan": "Sudan",
    "Suriname": "Suriname",
    "Sweden": "Sweden",
    "Switzerland": "Switzerland",
    "Syrian Arab Republic": "Syria",
    "Tajikistan": "Tajikistan",
    "Tanzania (United Republic of)": "Tanzania",
    "Togo": "Togo",
    "Tonga": "Tonga",
    "Trinidad and Tobago": "Trinidad and Tobago",
    "Tunisia": "Tunisia",
    "Turkey": "Türkiye",
    "Turkmenistan": "Turkmenistan",
    "Uganda": "Uganda",
    "Ukraine": "Ukraine",
    "United Arab Emirates": "United Arab Emirates",
    "United Kingdom": "United Kingdom",
    "United States of America": "United States",
    "Uruguay": "Uruguay",
    "Uzbekistan": "Uzbekistan",
    "Venezuela (Bolivarian Republic of)": "Venezuela",
    "Viet Nam": "Vietnam",
    "Yemen": "Yemen",
    "Zambia": "Zambia",
    "Zimbabwe": "Zimbabwe",
}

partida_award_llegada_wipo = {
    'China':'China',
    'Chinese Taipei':'China',
    'Macau (China)':'China',
    'Hong Kong':'China',
    'Taiwan':'China',
    # 'Israel':'Israel',
    # 'Palestine':'Israel',
    'United States':'United States',
    'Puerto Rico':'United States'
}

awards_pop = {
    "Albania": "Albania",
    "Argentina": "Argentina",
    "Armenia": "Armenia",
    "Australia": "Australia",
    "Austria": "Austria",
    "Azerbaijan": "Azerbaijan",
    "Bahrain": "Bahrain",
    "Bangladesh": "Bangladesh",
    "Belarus": "Belarus",
    "Belgium": "Belgium",
    "Bosnia and Herzegovina": "Bosnia and Herzegovina",
    "Botswana": "Botswana",
    "Brazil": "Brazil",
    "Bulgaria": "Bulgaria",
    "Cameroon": "Cameroon",
    "Canada": "Canada",
    "Cayman Islands": "Cayman Islands",
    "Chile": "Chile",
    "Colombia": "Colombia",
    "Costa Rica": "Costa Rica",
    "Croatia": "Croatia",
    "Cuba": "Cuba",
    "Cyprus": "Cyprus",
    "Czechia": "Czechia",
    "Denmark": "Denmark",
    "Dominican Republic": "Dominican Republic",
    "Ecuador": "Ecuador",
    "Estonia": "Estonia",
    "Faroe Islands": "Faroe Islands",
    "Finland": "Finland",
    "France": "France",
    "Georgia": "Georgia",
    "Germany": "Germany",
    "Greece": "Greece",
    "Guatemala": "Guatemala",
    "Hungary": "Hungary",
    "Iceland": "Iceland",
    "India": "India",
    "Indonesia": "Indonesia",
    "Iran": "Iran, Islamic Rep.",
    "Ireland": "Ireland",
    "Israel": "Israel",
    "Italy": "Italy",
    "Japan": "Japan",
    "Jordan": "Jordan",
    "Kazakhstan": "Kazakhstan",
    "Kenya": "Kenya",
    "Kosovo": "Kosovo",
    "Kuwait": "Kuwait",
    "Latvia": "Latvia",
    "Lebanon": "Lebanon",
    "Liechtenstein": "Liechtenstein",
    "Lithuania": "Lithuania",
    "Luxembourg": "Luxembourg",
    "Malaysia": "Malaysia",
    "Maldives": "Maldives",
    "Malta": "Malta",
    "Mexico": "Mexico",
    "Moldova": "Moldova",
    "Monaco": "Monaco",
    "Mongolia": "Mongolia",
    "Montenegro": "Montenegro",
    "Morocco": "Morocco",
    "Netherlands": "Netherlands",
    "New Zealand": "New Zealand",
    "Nicaragua": "Nicaragua",
    "Norway": "Norway",
    "Oman": "Oman",
    "Pakistan": "Pakistan",
    "Paraguay": "Paraguay",
    "Peru": "Peru",
    "Philippines": "Philippines",
    "Poland": "Poland",
    "Portugal": "Portugal",
    "Qatar": "Qatar",
    "Romania": "Romania",
    "Russia": "Russian Federation",
    "Saudi Arabia": "Saudi Arabia",
    "Serbia": "Serbia",
    "Singapore": "Singapore",
    "Slovenia": "Slovenia",
    "South Africa": "South Africa",
    "South Korea": "Korea, Rep.",
    "Spain": "Spain",
    "Sri Lanka": "Sri Lanka",
    "Sweden": "Sweden",
    "Switzerland": "Switzerland",
    "Tajikistan": "Tajikistan",
    "Tanzania": "Tanzania",
    "Thailand": "Thailand",
    "Trinidad and Tobago": "Trinidad and Tobago",
    "Tunisia": "Tunisia",
    "Ukraine": "Ukraine",
    "United Arab Emirates": "United Arab Emirates",
    "United Kingdom": "United Kingdom",
    "United States": "United States",
    "Uruguay": "Uruguay",
    "Venezuela": "Venezuela, RB",
    "Vietnam": "Viet Nam",
    "Zimbabwe": "Zimbabwe",
    "China": "China",
    'Egypt': "Egypt, Arab Rep.",
    'Kyrgyzstan': 'Kyrgyz Republic',
    'Laos': 'Lao PDR',
    'Macedonia': 'North Macedonia',
    'North Korea': 'Korea, Dem. People\'s Rep.',
    'Slovakia': 'Slovak Republic',
    'Swaziland': 'Eswatini',
    'Turkey': 'Turkiye'
}

wipo_pop = {
    "Albania": "Albania",
    "Algeria": "Algeria",
    "Andorra": "Andorra",
    "Antigua and Barbuda": "Antigua and Barbuda",
    "Argentina": "Argentina",
    "Armenia": "Armenia",
    "Australia": "Australia",
    "Austria": "Austria",
    "Azerbaijan": "Azerbaijan",
    "Bahamas": "Bahamas, The",
    "Bahrain": "Bahrain",
    "Bangladesh": "Bangladesh",
    "Barbados": "Barbados",
    "Belarus": "Belarus",
    "Belgium": "Belgium",
    "Belize": "Belize",
    "Benin": "Benin",
    "Bhutan": "Bhutan",
    "Bolivia (Plurinational State of)": "Bolivia",
    "Bonaire, Saint Eustatius and Saba": "Curacao",
    "Bosnia and Herzegovina": "Bosnia and Herzegovina",
    "Botswana": "Botswana",
    "Brazil": "Brazil",
    "Brunei Darussalam": "Brunei Darussalam",
    "Bulgaria": "Bulgaria",
    "Burkina Faso": "Burkina Faso",
    "Burundi": "Burundi",
    "Cambodia": "Cambodia",
    "Cameroon": "Cameroon",
    "Canada": "Canada",
    "Central African Republic": "Central African Republic",
    "Chad": "Chad",
    "Chile": "Chile",
    "China": "China",
    "Colombia": "Colombia",
    "Comoros": "Comoros",
    "Congo": "Congo, Rep.",
    "Costa Rica": "Costa Rica",
    "Croatia": "Croatia",
    "Cuba": "Cuba",
    "Curacao": "Curacao",
    "Cyprus": "Cyprus",
    "Czech Republic": "Czechia",
    "Céte d'ivoire": "Cote d'Ivoire",
    "Democratic Republic of the Congo": "Congo, Dem. Rep.",
    "Denmark": "Denmark",
    "Djibouti": "Djibouti",
    "Dominica": "Dominica",
    "Dominican Republic": "Dominican Republic",
    "Ecuador": "Ecuador",
    "Egypt": "Egypt, Arab Rep.",
    "El Salvador": "El Salvador",
    "Equatorial Guinea": "Equatorial Guinea",
    "Estonia": "Estonia",
    "Eswatini": "Eswatini",
    "Ethiopia": "Ethiopia",
    "Finland": "Finland",
    "France": "France",
    "Gabon": "Gabon",
    "Gambia": "Gambia, The",
    "Georgia": "Georgia",
    "Germany": "Germany",
    "Germany (West)": "Germany",
    "Ghana": "Ghana",
    "Greece": "Greece",
    "Grenada": "Grenada",
    "Guatemala": "Guatemala",
    "Guinea": "Guinea",
    "Guyana": "Guyana",
    "Haiti": "Haiti",
    "Holy See": 'Not classified',
    "Honduras": "Honduras",
    "Hungary": "Hungary",
    "Iceland": "Iceland",
    "India": "India",
    "Indonesia": "Indonesia",
    "Iran (Islamic Republic of)": "Iran, Islamic Rep.",
    "Iraq": "Iraq",
    "Ireland": "Ireland",
    "Israel": "Israel",
    "Italy": "Italy",
    "Jamaica": "Jamaica",
    "Japan": "Japan",
    "Jordan": "Jordan",
    "Kazakhstan": "Kazakhstan",
    "Kenya": "Kenya",
    "Korea (Democratic People's Republic of)": "Korea, Dem. People's Rep.",
    "Korea (Republic of)": "Korea, Rep.",
    "Kyrgyzstan": "Kyrgyz Republic",
    "Lao People's Democratic Republic": "Lao PDR",
    "Latvia": "Latvia",
    "Lebanon": "Lebanon",
    "Lesotho": "Lesotho",
    "Liberia": "Liberia",
    "Libya (State of)": "Libya",
    "Liechtenstein": "Liechtenstein",
    "Lithuania": "Lithuania",
    "Luxembourg": "Luxembourg",
    "Madagascar": "Madagascar",
    "Malawi": "Malawi",
    "Malaysia": "Malaysia",
    "Mali": "Mali",
    "Malta": "Malta",
    "Mauritania": "Mauritania",
    "Mauritius": "Mauritius",
    "Mexico": "Mexico",
    "Moldova (Republic of)": "Moldova",
    "Monaco": "Monaco",
    "Mongolia": "Mongolia",
    "Montenegro": "Montenegro",
    "Morocco": "Morocco",
    "Mozambique": "Mozambique",
    "Namibia": "Namibia",
    "Nepal": "Nepal",
    "Netherlands": "Netherlands",
    "New Zealand": "New Zealand",
    "Nicaragua": "Nicaragua",
    "Niger": "Niger",
    "Nigeria": "Nigeria",
    "North Macedonia (Republic of)": "North Macedonia",
    "Norway": "Norway",
    "Oman": "Oman",
    "Pakistan": "Pakistan",
    "Panama": "Panama",
    "Papua New Guinea": "Papua New Guinea",
    "Paraguay": "Paraguay",
    "Peru": "Peru",
    "Philippines": "Philippines",
    "Poland": "Poland",
    "Portugal": "Portugal",
    "Qatar": "Qatar",
    "Romania": "Romania",
    "Russian Federation": "Russian Federation",
    "Rwanda": "Rwanda",
    "Saint Kitts and Nevis": "St. Kitts and Nevis",
    "Saint Lucia": "St. Lucia",
    "Saint Vincent and the Grenadines": "St. Vincent and the Grenadines",
    "Samoa": "Samoa",
    "San Marino": "San Marino",
    "Sao Tome and Principe": "Sao Tome and Principe",
    "Saudi Arabia": "Saudi Arabia",
    "Senegal": "Senegal",
    "Serbia": "Serbia",
    "Serbia and Montenegro": "Serbia",
    "Seychelles": "Seychelles",
    "Sierra Leone": "Sierra Leone",
    "Singapore": "Singapore",
    "Sint Maarten (Dutch part)": "Sint Maarten (Dutch part)",
    "Slovakia": "Slovak Republic",
    "Slovenia": "Slovenia",
    "South Africa": "South Africa",
    "Spain": "Spain",
    "Sri Lanka": "Sri Lanka",
    "Sudan": "Sudan",
    "Suriname": "Suriname",
    "Sweden": "Sweden",
    "Switzerland": "Switzerland",
    "Syrian Arab Republic": "Syrian Arab Republic",
    "Tajikistan": "Tajikistan",
    "Tanzania (United Republic of)": "Tanzania",
    "Togo": "Togo",
    "Tonga": "Tonga",
    "Trinidad and Tobago": "Trinidad and Tobago",
    "Tunisia": "Tunisia",
    "Turkey": "Turkiye",
    "Turkmenistan": "Turkmenistan",
    "Uganda": "Uganda",
    "Ukraine": "Ukraine",
    "United Arab Emirates": "United Arab Emirates",
    "United Kingdom": "United Kingdom",
    "United States of America": "United States",
    "Uruguay": "Uruguay",
    "Uzbekistan": "Uzbekistan",
    "Venezuela (Bolivarian Republic of)": "Venezuela, RB",
    "Viet Nam": "Viet Nam",
    "Yemen": "Yemen, Rep.",
    "Zambia": "Zambia",
    "Zimbabwe": "Zimbabwe"
}

awards_wipo = {
    'Albania': 'Albania',
    'Argentina': 'Argentina',
    'Armenia': 'Armenia',
    'Australia': 'Australia',
    'Austria': 'Austria',
    'Azerbaijan': 'Azerbaijan',
    'Bahrain': 'Bahrain',
    'Bangladesh': 'Bangladesh',
    'Belarus': 'Belarus',
    'Belgium': 'Belgium',
    'Bosnia and Herzegovina': 'Bosnia and Herzegovina',
    'Botswana': 'Botswana',
    'Brazil': 'Brazil',
    'Bulgaria': 'Bulgaria',
    'Cameroon': 'Cameroon',
    'Canada': 'Canada',
    'Chile': 'Chile',
    'China': 'China',
    'Colombia': 'Colombia',
    'Costa Rica': 'Costa Rica',
    'Croatia': 'Croatia',
    'Cuba': 'Cuba',
    'Cyprus': 'Cyprus',
    'Czechia': 'Czech Republic',
    'Denmark': 'Denmark',
    'Dominican Republic': 'Dominican Republic',
    'Ecuador': 'Ecuador',
    'Egypt': 'Egypt',
    'Estonia': 'Estonia',
    'Finland': 'Finland',
    'France': 'France',
    'Georgia': 'Georgia',
    'Germany': 'Germany',
    'Greece': 'Greece',
    'Guatemala': 'Guatemala',
    'Hungary': 'Hungary',
    'Iceland': 'Iceland',
    'India': 'India',
    'Indonesia': 'Indonesia',
    'Iran': 'Iran (Islamic Republic of)',
    'Ireland': 'Ireland',
    'Israel': 'Israel',
    'Italy': 'Italy',
    'Japan': 'Japan',
    'Jordan': 'Jordan',
    'Kazakhstan': 'Kazakhstan',
    'Kenya': 'Kenya',
    'Kyrgyzstan': 'Kyrgyzstan',
    'Laos': "Lao People's Democratic Republic",
    'Latvia': 'Latvia',
    'Lebanon': 'Lebanon',
    'Liechtenstein': 'Liechtenstein',
    'Lithuania': 'Lithuania',
    'Luxembourg': 'Luxembourg',
    'Macedonia': 'North Macedonia (Republic of)',
    'Malaysia': 'Malaysia',
    'Malta': 'Malta',
    'Mexico': 'Mexico',
    'Monaco': 'Monaco',
    'Mongolia': 'Mongolia',
    'Montenegro': 'Montenegro',
    'Morocco': 'Morocco',
    'Netherlands': 'Netherlands',
    'New Zealand': 'New Zealand',
    'Nicaragua': 'Nicaragua',
    'North Korea': "Korea (Democratic People's Republic of)",
    'Norway': 'Norway',
    'Oman': 'Oman',
    'Pakistan': 'Pakistan',
    'Paraguay': 'Paraguay',
    'Peru': 'Peru',
    'Philippines': 'Philippines',
    'Poland': 'Poland',
    'Portugal': 'Portugal',
    'Qatar': 'Qatar',
    'Romania': 'Romania',
    'Russia': 'Russian Federation',
    'Saudi Arabia': 'Saudi Arabia',
    'Serbia': 'Serbia',
    'Singapore': 'Singapore',
    'Slovakia': 'Slovakia',
    'Slovenia': 'Slovenia',
    'South Africa': 'South Africa',
    'South Korea': 'Korea (Republic of)',
    'Spain': 'Spain',
    'Sri Lanka': 'Sri Lanka',
    'Swaziland': 'Eswatini',
    'Sweden': 'Sweden',
    'Switzerland': 'Switzerland',
    'Tajikistan': 'Tajikistan',
    'Tanzania': 'Tanzania (United Republic of)',
    'Trinidad and Tobago': 'Trinidad and Tobago',
    'Tunisia': 'Tunisia',
    'Turkey': 'Turkey',
    'Ukraine': 'Ukraine',
    'United Arab Emirates': 'United Arab Emirates',
    'United Kingdom': 'United Kingdom',
    'United States': 'United States of America',
    'Uruguay': 'Uruguay',
    'Venezuela': 'Venezuela (Bolivarian Republic of)',
    'Vietnam': 'Viet Nam',
    'Zimbabwe': 'Zimbabwe'
}

awards_OEC = {
    'Jordan': 'Jordan',
    'Romania': 'Romania',
    'Lebanon': 'Lebanon',
    'South Africa': 'South Africa',
    'France': 'France',
    'Kyrgyzstan': 'Kyrgyzstan',
    'Poland': 'Poland',
    'Chile': 'Chile',
    'Kenya': 'Kenya',
    'Malaysia': 'Malaysia',
    'Chinese Taipei': 'Chinese Taipei',
    'Canada': 'Canada',
    'Turkey': 'Turkey',
    'China': 'China',
    'Italy': 'Italy',
    'United States': 'United States',
    'Cuba': 'Cuba',
    'Pakistan': 'Pakistan',
    'Greece': 'Greece',
    'Norway': 'Norway',
    'Singapore': 'Singapore',
    'Venezuela': 'Venezuela',
    'Costa Rica': 'Costa Rica',
    'Georgia': 'Georgia',
    'Mongolia': 'Mongolia',
    'Brazil': 'Brazil',
    'Kuwait': 'Kuwait',
    'Switzerland': 'Switzerland',
    'Sri Lanka': 'Sri Lanka',
    'Sweden': 'Sweden',
    'Ireland': 'Ireland',
    'Laos': 'Laos',
    'Oman': 'Oman',
    'Guatemala': 'Guatemala',
    'Ecuador': 'Ecuador',
    'Ukraine': 'Ukraine',
    'Israel': 'Israel',
    'Saudi Arabia': 'Saudi Arabia',
    'Botswana': 'Botswana',
    'Albania': 'Albania',
    'Austria': 'Austria',
    'Tanzania': 'Tanzania',
    'Egypt': 'Egypt',
    'Germany': 'Germany',
    'Bulgaria': 'Bulgaria',
    'Moldova': 'Moldova',
    'Uruguay': 'Uruguay',
    'United Arab Emirates': 'United Arab Emirates',
    'New Zealand': 'New Zealand',
    'Azerbaijan': 'Azerbaijan',
    'Bosnia and Herzegovina': 'Bosnia and Herzegovina',
    'Bangladesh': 'Bangladesh',
    'Croatia': 'Croatia',
    'Tajikistan': 'Tajikistan',
    'Russia': 'Russia',
    'Hong Kong': 'Hong Kong',
    'Spain': 'Spain',
    'Vietnam': 'Vietnam',
    'Slovakia': 'Slovakia',
    'Indonesia': 'Indonesia',
    'Iran': 'Iran',
    'Kazakhstan': 'Kazakhstan',
    'Portugal': 'Portugal',
    'Mexico': 'Mexico',
    'North Korea': 'North Korea',
    'Qatar': 'Qatar',
    'Nicaragua': 'Nicaragua',
    'Australia': 'Australia',
    'Philippines': 'Philippines',
    'India': 'India',
    'Hungary': 'Hungary',
    'Slovenia': 'Slovenia',
    'Peru': 'Peru',
    'Lithuania': 'Lithuania',
    'Paraguay': 'Paraguay',
    'United Kingdom': 'United Kingdom',
    'Belgium': 'Belgium',
    'Denmark': 'Denmark',
    'Thailand': 'Thailand',
    'Japan': 'Japan',
    'Dominican Republic': 'Dominican Republic',
    'Belarus': 'Belarus',
    'Colombia': 'Colombia',
    'Czechia': 'Czechia',
    'South Korea': 'South Korea',
    'Argentina': 'Argentina',
    'Tunisia': 'Tunisia',
    'Serbia': 'Serbia',
    'Netherlands': 'Netherlands',
    'Finland': 'Finland',
    'Cameroon': 'Cameroon',
    'Armenia': 'Armenia',
    'Zimbabwe': 'Zimbabwe',
    'Morocco': 'Morocco'
}