award_iso = {
    "Albania": "AL",
    "Argentina": "AR",
    "Armenia": "AM",
    "Australia": "AU",
    "Austria": "AT",
    "Azerbaijan": "AZ",
    "Bahrain": "BH",
    "Bangladesh": "BD",
    "Belarus": "BY",
    "Belgium": "BE",
    "Bosnia and Herzegovina": "BA",
    "Botswana": "BW",
    "Brazil": "BR",
    "Bulgaria": "BG",
    "Cameroon": "CM",
    "Canada": "CA",
    "Cayman Islands": "KY",
    "Chile": "CL",
    "China": "CN",
    "Chinese Taipei": "TW",
    "Colombia": "CO",
    "Costa Rica": "CR",
    "Croatia": "HR",
    "Cuba": "CU",
    "Cyprus": "CY",
    "Czechia": "CZ",
    "Denmark": "DK",
    "Dominican Republic": "DO",
    "Ecuador": "EC",
    "Egypt": "EG",
    "Estonia": "EE",
    "Faroe Islands": "FO",
    "Finland": "FI",
    "France": "FR",
    "Georgia": "GE",
    "Germany": "DE",
    "Greece": "GR",
    "Guatemala": "GT",
    "Hong Kong": "HK",
    "Hungary": "HU",
    "Iceland": "IS",
    "India": "IN",
    "Indonesia": "ID",
    "Iran": "IR",
    "Ireland": "IE",
    "Israel": "IL",
    "Italy": "IT",
    "Japan": "JP",
    "Jordan": "JO",
    "Kazakhstan": "KZ",
    "Kenya": "KE",
    "Kosovo": "XK",
    "Kuwait": "KW",
    "Kyrgyzstan": "KG",
    "Laos": "LA",
    "Latvia": "LV",
    "Lebanon": "LB",
    "Liechtenstein": "LI",
    "Lithuania": "LT",
    "Luxembourg": "LU",
    "Macau (China)": "MO",
    "Macedonia": "MK",
    "Malaysia": "MY",
    "Maldives": "MV",
    "Malta": "MT",
    "Mexico": "MX",
    "Moldova": "MD",
    "Monaco": "MC",
    "Mongolia": "MN",
    "Montenegro": "ME",
    "Morocco": "MA",
    "Netherlands": "NL",
    "New Zealand": "NZ",
    "Nicaragua": "NI",
    "North Korea": "KP",
    "Norway": "NO",
    "Oman": "OM",
    "Pakistan": "PK",
    "Palestine": "PS",
    "Paraguay": "PY",
    "Peru": "PE",
    "Philippines": "PH",
    "Poland": "PL",
    "Portugal": "PT",
    "Puerto Rico": "PR",
    "Qatar": "QA",
    "Romania": "RO",
    "Russia": "RU",
    "Saudi Arabia": "SA",
    "Serbia": "RS",
    "Singapore": "SG",
    "Slovakia": "SK",
    "Slovenia": "SI",
    "South Africa": "ZA",
    "South Korea": "KR",
    "Spain": "ES",
    "Sri Lanka": "LK",
    "Swaziland": "SZ",
    "Sweden": "SE",
    "Switzerland": "CH",
    "Taiwan": "TW",
    "Tajikistan": "TJ",
    "Tanzania": "TZ",
    "Thailand": "TH",
    "Trinidad and Tobago": "TT",
    "Tunisia": "TN",
    "Turkey": "TR",
    "Ukraine": "UA",
    "United Arab Emirates": "AE",
    "United Kingdom": "GB",
    "United States": "US",
    "Uruguay": "UY",
    "Venezuela": "VE",
    "Vietnam": "VN",
    "Zimbabwe": "ZW"
}

wipo_iso  = {
    "Albania": "AL",
    "Algeria": "DZ",
    "Andorra": "AD",
    "Antigua and Barbuda": "AG",
    "Argentina": "AR",
    "Armenia": "AM",
    "Australia": "AU",
    "Austria": "AT",
    "Azerbaijan": "AZ",
    "Bahamas": "BS",
    "Bahrain": "BH",
    "Bangladesh": "BD",
    "Barbados": "BB",
    "Belarus": "BY",
    "Belgium": "BE",
    "Belize": "BZ",
    "Benin": "BJ",
    "Bhutan": "BT",
    "Bolivia (Plurinational State of)": "BO",
    "Bonaire, Saint Eustatius and Saba": "BQ",
    "Bosnia and Herzegovina": "BA",
    "Botswana": "BW",
    "Brazil": "BR",
    "Brunei Darussalam": "BN",
    "Bulgaria": "BG",
    "Burkina Faso": "BF",
    "Burundi": "BI",
    "Cambodia": "KH",
    "Cameroon": "CM",
    "Canada": "CA",
    "Central African Republic": "CF",
    "Chad": "TD",
    "Chile": "CL",
    "China": "CN",
    "Colombia": "CO",
    "Comoros": "KM",
    "Congo": "CG",
    "Costa Rica": "CR",
    "Croatia": "HR",
    "Cuba": "CU",
    "Curacao": "CW",
    "Cyprus": "CY",
    "Czech Republic": "CZ",
    "Côte d'Ivoire": "CI",
    "Democratic Republic of the Congo": "CD",
    "Denmark": "DK",
    "Djibouti": "DJ",
    "Dominica": "DM",
    "Dominican Republic": "DO",
    "Ecuador": "EC",
    "Egypt": "EG",
    "El Salvador": "SV",
    "Equatorial Guinea": "GQ",
    "Estonia": "EE",
    "Eswatini": "SZ",
    "Ethiopia": "ET",
    "Finland": "FI",
    "France": "FR",
    "Gabon": "GA",
    "Gambia": "GM",
    "Georgia": "GE",
    "Germany": "DE",
    "Germany (West)": "DE",
    "Ghana": "GH",
    "Greece": "GR",
    "Grenada": "GD",
    "Guatemala": "GT",
    "Guinea": "GN",
    "Guyana": "GY",
    "Haiti": "HT",
    "Holy See": "VA",
    "Honduras": "HN",
    "Hungary": "HU",
    "Iceland": "IS",
    "India": "IN",
    "Indonesia": "ID",
    "Iran (Islamic Republic of)": "IR",
    "Iraq": "IQ",
    "Ireland": "IE",
    "Israel": "IL",
    "Italy": "IT",
    "Jamaica": "JM",
    "Japan": "JP",
    "Jordan": "JO",
    "Kazakhstan": "KZ",
    "Kenya": "KE",
    "Korea (Democratic People's Republic of)": "KP",
    "Korea (Republic of)": "KR",
    "Kyrgyzstan": "KG",
    "Lao People's Democratic Republic": "LA",
    "Latvia": "LV",
    "Lebanon": "LB",
    "Lesotho": "LS",
    "Liberia": "LR",
    "Libya (State of)": "LY",
    "Liechtenstein": "LI",
    "Lithuania": "LT",
    "Luxembourg": "LU",
    "Madagascar": "MG",
    "Malawi": "MW",
    "Malaysia": "MY",
    "Mali": "ML",
    "Malta": "MT",
    "Mauritania": "MR",
    "Mauritius": "MU",
    "Mexico": "MX",
    "Moldova (Republic of)": "MD",
    "Monaco": "MC",
    "Mongolia": "MN",
    "Montenegro": "ME",
    "Morocco": "MA",
    "Mozambique": "MZ",
    "Namibia": "NA",
    "Nepal": "NP",
    "Netherlands": "NL",
    "New Zealand": "NZ",
    "Nicaragua": "NI",
    "Niger": "NE",
    "Nigeria": "NG",
    "North Macedonia (Republic of)": "MK",
    "Norway": "NO",
    "Oman": "OM",
    "Pakistan": "PK",
    "Panama": "PA",
    "Papua New Guinea": "PG",
    "Paraguay": "PY",
    "Peru": "PE",
    "Philippines": "PH",
    "Poland": "PL",
    "Portugal": "PT",
    "Qatar": "QA",
    "Romania": "RO",
    "Russian Federation": "RU",
    "Rwanda": "RW",
    "Saint Kitts and Nevis": "KN",
    "Saint Lucia": "LC",
    "Saint Vincent and the Grenadines": "VC",
    "Samoa": "WS",
    "San Marino": "SM",
    "Sao Tome and Principe": "ST",
    "Saudi Arabia": "SA",
    "Senegal": "SN",
    "Serbia": "RS",
    "Serbia and Montenegro": "CS",
    "Seychelles": "SC",
    "Sierra Leone": "SL",
    "Singapore": "SG",
    "Sint Maarten (Dutch part)": "SX",
    "Slovakia": "SK",
    "Slovenia": "SI",
    "South Africa": "ZA",
    "Spain": "ES",
    "Sri Lanka": "LK",
    "Sudan": "SD",
    "Suriname": "SR",
    "Sweden": "SE",
    "Switzerland": "CH",
    "Syrian Arab Republic": "SY",
    "Tajikistan": "TJ",
    "Tanzania (United Republic of)": "TZ",
    "Togo": "TG",
    "Tonga": "TO",
    "Trinidad and Tobago": "TT",
    "Tunisia": "TN",
    "Turkey": "TR",
    "Turkmenistan": "TM",
    "Uganda": "UG",
    "Ukraine": "UA",
    "United Arab Emirates": "AE",
    "United Kingdom": "GB",
    "United States of America": "US",
    "Uruguay": "UY",
    "Uzbekistan": "UZ",
    "Venezuela (Bolivarian Republic of)": "VE",
    "Viet Nam": "VN",
    "Yemen": "YE",
    "Zambia": "ZM",
    "Zimbabwe": "ZW"
}

awards_gdp = { #paises_awards: paises_gdp
    "United States": "United States",
    "Italy": "Italy",
    "United Kingdom": "United Kingdom",
    "Germany": "Germany",
    "Turkey": "Türkiye, Republic of",
    "South Korea": "Korea, Republic of",
    "Canada": "Canada",
    "Hungary": "Hungary",
    "Russia": "Russian Federation",
    "Spain": "Spain",
    "Australia": "Australia",
    "Netherlands": "Netherlands",
    "India": "India",
    "Czechia": "Czech Republic",
    "Iran": "Iran",
    "France": "France",
    "Israel": "Israel",
    "Brazil": "Brazil",
    "Singapore": "Singapore",
    "Portugal": "Portugal",
    "Austria": "Austria",
    "Hong Kong": "Hong Kong SAR",
    "Switzerland": "Switzerland",
    "Belgium": "Belgium",
    "Denmark": "Denmark",
    "Sweden": "Sweden",
    "Thailand": "Thailand",
    "China": "China, People's Republic of",
    "Egypt": "Egypt",
    "Lithuania": "Lithuania",
    "Poland": "Poland",
    "Finland": "Finland",
    "Serbia": "Serbia",
    "Greece": "Greece",
    "Japan": "Japan",
    "Mexico": "Mexico",
    "Bulgaria": "Bulgaria",
    "Ireland": "Ireland",
    "Ukraine": "Ukraine",
    "Romania": "Romania",
    "United Arab Emirates": "United Arab Emirates",
    "Latvia": "Latvia",
    "New Zealand": "New Zealand",
    "Argentina": "Argentina",
    "Croatia": "Croatia",
    "Malaysia": "Malaysia",
    "Vietnam": "Vietnam",
    "Slovenia": "Slovenia",
    "Taiwan": "Taiwan Province of China",
    "Chinese Taipei": "Taiwan Province of China",
    "Indonesia": "Indonesia",
    "Philippines": "Philippines",
    "Slovakia": "Slovak Republic",
    "Saudi Arabia": "Saudi Arabia",
    "Chile": "Chile",
    "Estonia": "Estonia",
    "Norway": "Norway",
    "South Africa": "South Africa",
    "Jordan": "Jordan",
    "Lebanon": "Lebanon",
    "Peru": "Peru",
    "Colombia": "Colombia",
    "Cyprus": "Cyprus",
    "Guatemala": "Guatemala",
    "Kazakhstan": "Kazakhstan",
    "Qatar": "Qatar",
    "Armenia": "Armenia",
    "Georgia": "Georgia",
    "Iceland": "Iceland",
    "Moldova": "Moldova",
    "Pakistan": "Pakistan",
    "Belarus": "Belarus",
    "Bosnia and Herzegovina": "Bosnia and Herzegovina",
    "Kyrgyzstan": "Kyrgyz Republic",
    "Bangladesh": "Bangladesh",
    "Dominican Republic": "Dominican Republic",
    "Ecuador": "Ecuador",
    "Kuwait": "Kuwait",
    "Uruguay": "Uruguay",
    "Macau (China)": "Macao SAR",
}

partida_award_llegada_wipo = {
    'China':'China',
    'Chinese Taipei':'China',
    'Macau (China)':'China',
    'Hong Kong':'China',
    'Macau':'China',
    'Taiwan':'China',
    'Israel':'Israel',
    'Palestine':'Israel',
    'United States':'United States of America',
    'Puerto Rico':'United States of America'
}